Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> Hey Sahil, ../testing/quads-sandbox.sh should have no problems now with lib.Foreman.  There's also an option added to ../conf/quads.yml to opt out of Foreman host health checks (default being to opt-out).
> 
> We're ready whenever you want to rebase/resubmit this patchset as needed.  Thanks for your awesome work thus far.

Hi Will,
So I solved the above problem I mentioned. Now I am stuck with 2 new problems ( 1 step forward, 2 step backward :) 

One is a gerrit issue. I am not well versed with the gerrit workflow and it is not letting me submit a new patch set. Something to do with the merge conflicts because the changes I pulled. 
here is the error:
"""
[jack@quadshil gerrit_quads]$ git commit --amend
fatal: You are in the middle of a merge -- cannot amend.
[jack@quadshil gerrit_quads]$ git review
Enter passphrase for key '/home/jack/.ssh/id_rsa': 
Errors running git rebase -p -i remotes/gerrit/master
Cannot rebase: Your index contains uncommitted changes.
Please commit or stash them.
It is likely that your change has a merge conflict. You may resolve it
in the working tree now as described above and then run 'git review'
again, or if you do not want to resolve it yet (note that the change
can not merge until the conflict is resolved) you may run 'git rebase
--abort' then 'git review -R' to upload the change without rebasing.
"""
Any advise will be helpful. 

Second is on the code side, once I fixed the import issues, the api call I added is getting a 403 error. The call is being dropped before even quads-daemon is accessed. Has anything changed that would invoke such behavior ?

Here is the error when I run: 
"""
(.quads) [jack@quadshil quads]$ $quads_cmd --show-reservations
Traceback (most recent call last):
  File "/home/jack/git/quads/bin/quads-cli", line 614, in <module>
    main()
  File "/home/jack/git/quads/bin/quads-cli", line 132, in main
    response = urllib2.urlopen(url, timeout=120)
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1230, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1200, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 111] Connection refused>
"""

Patch-set: 1
Reviewer: Sahil Tikale <1013989@d5d70762-12d0-45a1-890d-524b12d3f735>