fix: disable abrtd, postgres db init error, docs
There is an error that appears during first-time RPM installation and
perhaps upgrades where the postgres DB structure at /opt/quads/db/data
is not empty prior to initializing it, this is not fatal and I think can
be ignored.

 * Initializing database in '/opt/quads/db/data'
ERROR: Data directory /opt/quads/db/data is not empty!
ERROR: Initializing database failed, possibly see /var/lib/pgsql/initdb_quads-db.log

I'm not actually able to replicate this even after removing everything,
clearing all data and re-installing but let's keep it quiet because it's
not fatal to installation workflow.

Additionally, abrtd (another bug reporting tool) seems to be overstepping
its bounds to trigger an selinux issue, it appears to be some Fedora
packaging / signing key issue but let's just disable and stop it as we
don't need it for QUADS, nor do people probably want to have automatic
bug submission and data sent to Fedora.

Sep 18 09:24:37 localhost.localdomain abrt-server[2367]: Package 'python3-flask' isn't signed with proper key
Sep 18 09:24:37 localhost.localdomain abrt-server[2367]: 'post-create' on '/var/spool/abrt/Python3-2024-09-18-09:24:36-2357' exited with 1

and this triggers:

type=AVC msg=audit(1725886183.680:542): avc:  denied  { nnp_transition } for  pid=2590 comm="abrt-server" scontex t=system_u:system_r:abrt_t:s0-s0:c0.c1023 tcontext=system_u:system_r:abrt_handle_event_t:s0-s0:c0.c1023 tclass=pr ocess2 permissive=0

Lastly, update some documentation that is out of date:

* cloud01 is auto-created now
* --model is required for adding new hosts

Change-Id: Iae2e83063091c625d9a38ac390f8f37a790ecf8e